apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vuejs-ingress
  labels:
    app: vuejs
  annotations:
    kubernetes.io/ingress.global-static-ip-name: vuejs-ip
    networking.gke.io/managed-certificates: vuejs-certificate
spec:
  rules:
    - host: vishalweb.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vuejs-service
                port:
                  number: 80
