on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build and push a docker image

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

   
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: sitharamaneesh
        password: sitharasarath

    - name: Build, tag, and push the image to Docker Hub
      id: build-image
      env:
        DOCKERHUB_USERNAME: sitharamaneesh
        DOCKERHUB_REPOSITORY: your-dockerhub-username/your-docker-image-repo
        IMAGE_TAG: latest  # You can change this tag as needed
      run: |
        # Build a Docker container and push it to Docker Hub
        docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to Docker Hub..."
        docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$DOCKERHUB_REPOSITORY:$IMAGE_TAG"
