name: Deploy to GKE and Another GKE

on:
  push:
    branches:
      - main

jobs:
  deploy_gke_us_east4:
    runs-on: self-hosted 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: gcp_auth_us_east4  # Give a unique ID for this step
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set GCP Project ID for GKE in us-east4
        run: gcloud config set project nifty-altar-394805
      
      - name: Set GKE Cluster in us-east4
        run: gcloud container clusters get-credentials cluster-dev --zone us-east4

      - name: Deploy to GKE in us-east4
        run : | 
              kubectl delete -f vuejs-deployment.yaml
  deploy_gke_europe_north1:
    environment: 'main'  # This line was moved here, and the syntax was corrected.
    runs-on: self-hosted

    needs: deploy_gke_us_east4  # Wait for the 'deploy_gke_us_east4' job to finish successfully before starting this job.

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: gcp_auth_europe_north1  # Give a unique ID for this step
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set GCP Project ID for GKE in europe-north1
        run: gcloud config set project nifty-altar-394805
      
      - name: Set GKE Cluster in europe-north1
        run: gcloud container clusters get-credentials cluster-prod --zone europe-north1

      - name: Deploy to GKE in europe-north1
        run : | 
              kubectl delete -f vuejs-deployment.yaml

  deploy_gke_us_central1:
    runs-on: self-hosted

    needs: deploy_gke_europe_north1  # Wait for the 'deploy_gke_europe_north1' job to finish successfully before starting this job.

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: gcp_auth_us_central1  # Give a unique ID for this step
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set GCP Project ID for GKE in us-central1
        run: gcloud config set project nifty-altar-394805
      
      - name: Set GKE Cluster in us-central1
        run: gcloud container clusters get-credentials cluster-dr --zone us-central1

      - name: Deploy to GKE in us-central1
        run : | 
              kubectl delete -f vuejs-deployment.yaml
        
