name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure gcloud credentials
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          version: '343.0.0'
          project_id: "nifty-altar-394805"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set GCP Project ID
        run: gcloud config set project nifty-altar-394805
      
      - name: Set GKE Cluster
        run: gcloud container clusters get-credentials cluster-prod --zone europe-north1-a

      - name: Install kubectl
        run: |
          sudo yum install google-cloud-sdk-gke-gcloud-auth-plugin
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          

      # Deploy to GKE
      
      - name: Deploy to GKE
        run: |
          kubectl apply -f vuejs-deployment.yaml


      

